version: '3'
services:
  frontend:
    container_name: rest_front_end
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /auto-rest-front
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    volumes:
      - ./frontend:/auto-rest-front
    stdin_open: true
    tty: true
    restart: on-failure
